=== 9circuits/Beacon/repodoc-web/validate/repodoc-result.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="repodoc-result" type="repodoc"/>
    
    <xs:complexType name="repodoc">
        <xs:sequence>
            <xs:element name="module" type="rmodule" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="rmodule">
        <xs:sequence>
            <xs:element name="reason" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="moduleDesc"/>
    </xs:complexType>
    
    <xs:attributeGroup name="moduleDesc">
        
        <xs:attribute name="id">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="banned"/>
                    <xs:enumeration value="header"/>
                    <xs:enumeration value="length"/>
                    <xs:enumeration value="links"/>
                    <xs:enumeration value="path"/>
                    <xs:enumeration value="utf8"/>
                    <xs:enumeration value="xml"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        
        <xs:attribute name="result">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="ok"/>
                    <xs:enumeration value="warning"/>
                    <xs:enumeration value="critical"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        
    </xs:attributeGroup>
    
</xs:schema>

=== 9circuits/Beacon/repodoc-web/validate/template.xml
<?xml version="1.0" encoding="UTF-8"?>
<repodoc-result xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="repodoc-result.xsd">

    <module id="banned" result="ok">
        <reason/>
    </module>

    <module id="header" result="ok">
        <reason/>
    </module>

    <module id="length" result="ok">
        <reason/>
    </module>

    <module id="links" result="ok">
        <reason/>
    </module>

    <module id="path" result="ok">
        <reason/>
    </module>

    <module id="utf8" result="ok">
        <reason/>
    </module>

    <module id="xml" result="ok">
        <reason/>
    </module>

</repodoc-result>
