=== 9circuits/Beacon/editor/xml/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="beacon-config" type="bconfig"/>
    
    <xs:complexType name="bconfig">
	<xs:sequence>
            <xs:element name="metadata" type="mdata"/>
	    <xs:element name="tools" type="tdata"/>
	    <xs:element name="tree" type="tree"/>
            <xs:element name="inline" type="tinymce"/>
	    <xs:element name="pre" type="tinymce"/>
	    <xs:element name="tabs" type="tabs"/>
	    <xs:element name="footer" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="mdata">
        <xs:sequence>
            <xs:element name="field" type="field" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tabs">
        <xs:sequence>
            <xs:element name="tab" type="tfield" maxOccurs="unbounded"/>
	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="tdata">
        <xs:sequence>
            <xs:element name="field" type="tool" maxOccurs="unbounded"/>
	</xs:sequence>
	<xs:attribute name="label" type="xs:string" use="required"/>
	<xs:atrribute name="icon" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="tree">
    	<xs:attribute name="label" type="xs:string" use="required"/>
	<xs:atrribute name="icon" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="tinymce">
        
    </xs:complexType>
    
    <xs:complexType name="tfield">
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="label" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="tool">
        <xs:attribute name="label" type="xs:string" use="required"/>
        <xs:attribute name="caption" type="xs:string" use="required"/>
        <xs:attribute name="guide" type="xs:string" use="required"/>
        <xs:attribute name="icon" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="field">
        <xs:attribute name="label" type="xs:string" use="required"/>
        <xs:attribute name="caption" type="xs:string" use="required"/>
        <xs:attribute name="guide" type="xs:string" use="required"/>
        <xs:attribute name="fnote" type="xs:string" use="required"/>
        <xs:attribute name="icon" type="xs:string" use="required"/>
    </xs:complexType>
    
</xs:schema>

=== 9circuits/Beacon/editor/xml/default-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<beacon-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="config.xsd">
    
    <!-- No need to translate! -->           
    <version>0.2</version>

    <!-- Translate only label, caption and fnote -->
    <metadata cancelLabel="Cancel" cancelIcon="cancel.png" errorIcon="error.png">
        <field label="Title" caption="The Title of the Document" guide="title" fnote="Enter a descriptive but short name for the document" icon="title.png"/>
        <field label="Author" caption="Author(s) of the Document" guide="author" fnote="You may add additional authors and email information later" icon="authors.png"/>
        <field label="Abstract" caption="A Short summary of the Document" guide="abstract" fnote="This text will appear in the top-right corner of the document" icon="abstract.png"/>
        <field label="Date" caption="Date of Creation" guide="date" fnote="Use the YYYY-MM-DD format!" icon="date.png"/>
    </metadata>

    <!-- Translate only label and caption -->
    <tools label="Toolbox" icon="tools.png">
        <field label="Chapter" caption="Inserts a new Chapter" guide="chapter" icon="chapter.png"/>
	    <field label="Section" caption="Inserts a new Section" guide="section" icon="section.png"/>
        <field label="Paragraph" caption="Add a Paragraph" guide="p" icon="paragraph.png"/>
        <field label="Note" caption="Add a Note" guide="note" icon="note.png"/>
        <field label="Warning" caption="Add a Warning" guide="warning" icon="warning.png"/>
        <field label="Important" caption="Add some Important text" guide="impo" icon="important.png"/>
        <field label="Figure" caption="Add an Image" guide="figure" icon="figure.png"/>
        <field label="Table" caption="Add a Table" guide="table" icon="table.png"/>
        <field label="Unordered List" caption="Add an Unordered list" guide="ul" icon="unorderedlist.png"/>
        <field label="Ordered List" caption="Add an Ordered list" guide="ol" icon="orderedlist.png"/>
        <field label="Definition List" caption="Add a Definition list" guide="dl" icon="definitionlist.png"/>
    </tools>

    <!-- Translate only label -->
    <tree label="DOM Tree" icon="tree.png"/>

    <inline/>
    
    <pre/>

    <!-- Translate only label -->
    <tabs>
	    <tab id="tab1" label="Design"/>
	    <tab id="tab2" label="Source"/>
    </tabs>

    <!-- Translate whole text, this is prefixed by: Beacon <version> -->
    <footer>
        <![CDATA[ &copy; 2006 The Gentoo Foundation ]]>
    </footer>

</beacon-config>
